---
services:
  aws.greengrass.Nucleus:
    configuration:
      runWithDefault:
        posixUser: nobody
        windowsUser: integ-tester
  bar:
    lifecycle:
      run: echo bar-service
  main:
    dependencies:
      - bar
      - aws.greengrass.Nucleus
